services:
  docs:
    image: chhad_mailtrack_local_docs
    container_name: chhad_mailtrack_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./chhad_mailtrack:/app/chhad_mailtrack:z
    ports:
      - '9000:9000'
    command: /start-docs
